version: "3"

services:
  app:
    image: Lab_fis_Open:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host